tools:
  php_analyzer:
    enabled: true
    filter:
      excluded_paths: 
        - spec/*
  php_pdepend:
    enabled: true
    filter:
      excluded_paths:
        - spec/*
  php_code_sniffer:
    enabled: true
    filter:
      excluded_paths:
        - spec/*
  php_cs_fixer:
    enabled: true
    filter:
      excluded_paths:
        - spec/*
  external_code_coverage: true
