<?php
namespace Modelo;
use Purekid\Mongodm\Model;

class ModeloConductor extends Model {

        static $collection = "conductores";

        /** use specific config section **/
        public static $config = 'default';

           protected static $attrs = array(

               "plus" => '',
               "dni" => '',
               "nombre" => '',
               "apellido" => '',
               "ant_penales" => '',
               "ant_judicial" => '',
               "ant_policial" => '',
               "record_cond" => '',
               "resultado" => '',
               "pdf" => '',
               "placa" => '',
               "soat" => '',
               "observacion" => '',
               "validarpdf" => 0,
               "empresa" => '',
               "blacklist" => null,
               "fechaentrega" => '',
               "estado_civil" => '',
               "secuencia_arhu_ant" => '',
               "fecha_soat" => '',
               "orden_captura" => '',
               "fecha_inicio_soat" => '',
               "fecha_fin_soat" => '',
               "fecha_nacimiento" => '',
               "nombrecompania" => '',
               "numeropoliza" => '',
               "NombreUsoVehiculo" => '',
               "nombreclasevehiculo" => '',
               "fechacontrolpolicial" => '',
               "TipoCertificado" => '',
               "cabify" => 0,
               "easytaxi" => 0,
               "easyeconomy" => 0,
               "observacionPenales" => '',
               "observacionJudicial" => '',
               "observacionPolicial" => '',
               "motivo_penal" => '',
               "autoridad_penal" => '',
               "documento_penal" => '',
               "fecha_proceso_penal" => '',
               "estado_penal" => '',
               "tipo_ocurrecia_penal" => '',
               "tipo_penal" => '',
               "agraviado_penal" => '',
               "definicion_delito_penal" => '',
               "motivo_Policial" => '',
               "autoridad_Policial" => '',
               "documento_Policial" => '',
               "fecha_proceso_Policial" => '',
               "estado_Policial" => '',
               "tipo_ocurrecia_Policial" => '',
               "tipo_Policial" => '',
               "agraviado_Policial" => '',
               "definicion_delito_Policial" => '',
               "motivo_judicial" => '',
               "autoridad_judicial" => '',
               "documento_judicial" => '',
               "fecha_proceso_judicial" => '',
               "estado_judicial" => '',
               "tipo_ocurrecia_judicial" => '',
               "tipo_judicial" => '',
               "agraviado_judicial" => '',
               "definicion_delito_judicial" => '',
               "fecha_foto" => '',
               "fecha_dni_digital" => '',
               "extr" => 0,
               "fecha_act" => '',
               "act" => 0,
               "form" => '',
               "act_cbf" => 0,
               "act_easy" => 0,
               "fecha_dni_digital_r" => '',
               "fecha_migrados" => '',
               "migrarcabf" => 0,
               "migrareasy" => 0,
               "fechamigra" => '',
               "color_vehiculo" => '',
               "fecha_actsoat" => '',
               "contsoat" => 0,
               "actualizado" => 0,
               "foto_cbf" => '',
               "fecha_foto_cbf" => '',
               "fecha_placa" => '',
               "contador_act_placa" => 0,
               "fecha_act_placa" => '',
               "fecha_fab_veh" => '',
               "cambio_placa" => '',
               "ruc" => null,
               "status_licencia" => null,
               "id_provincia" => 7

        );
}

?>